### ISSUE TITLE
Image only loads after entire image enters viewport

### ISSUE THREAD

**Issue by vinaybedre** [imbhargav5/react-lazy-progressive-image#8] opened 2018-09-26 15:36 UTC
Hi,

See the code sample at https://codesandbox.io/s/m94pp34x9y
Until the entire image do not come under the viewport, the actual image wont get loaded. Can you please help how to fix this?
For me it either looks like I am missing something or there is issue with the framework.

The actual behavior should have been that as soon the top of the image enters the viewport, the actual image should get loaded up.

The issue occurs when I specify the height for image.

![bug](https://user-images.githubusercontent.com/2630384/46091135-cc9c8180-c1cf-11e8-8edf-135e81b94326.PNG)

**Comment by imbhargav5** [comment] 2018-09-26 16:09
Hey @vinaybedre , you can use visibilitySensorProps and get it to work. 
```jsx
    <LazyImage
          placeholder="https://images-eu.ssl-images-amazon.com/images/I/41fT611rSBL._SL10_.jpg"
          src="https://images-eu.ssl-images-amazon.com/images/I/41fT611rSBL.jpg"
          visibilitySensorProps={{
            partialVisibility: true
          }}
        >
          {(src, _loading, srcSetData) => (
            <img
              id="productImg"
              class="img-fluid img-responsive rounded mx-auto d-block"
              style="height:400px;width:auto;"
              src={src}
            />
          )}
        </LazyImage>

```

Try this :) https://codesandbox.io/s/qln785vo4w

**Comment by imbhargav5** [comment] 2018-09-26 17:09
Closing this, since it's not a bug, but a usability issue.

**Closed as completed by imbhargav5** 2018-09-26 17:09 UTC
Labels: usage

**Comment by vinaybedre** [comment] 2018-09-27 02:03
Thanks @imbhargav5. That helped.

partialVisibility should be set to true to work.

**Comment by imbhargav5** [comment] 2018-09-27 02:30
Oh yeah haha I was testing with true and false. Pasted the wrong snippet.
